---
title: "R Notebook"
output: html_notebook
---


```{r}
library(RMariaDB)
```

```{r}
localuserpassword <- "practicum_1"
```

```{r}
birdstrikedb <- dbConnect(RMariaDB::MariaDB(), user='balajiramanathan_p', password=localuserpassword, dbname='birdstrikedata', host='localhost')
dbListTables(birdstrikedb)
```

```{sql connection=birdstrikedb}
CREATE TABLE Airport 
(
  AirportName VARCHAR(80) DEFAULT 'Unknown',
  State VARCHAR(30) DEFAULT 'N/A',
  PRIMARY KEY(AirportName, State)
);
```

```{sql connection=birdstrikedb}
CREATE TABLE Aircraft 
(
  Model VARCHAR(20) DEFAULT 'Unknown',
  Type enum('Airplane', 'Unknown') DEFAULT 'Unknown',
  isLarge Boolean DEFAULT FALSE,
  PRIMARY KEY(Model)
);
```

```{sql connection=birdstrikedb}
CREATE TABLE Altitude
(
  Altitude INT PRIMARY KEY CHECK(Altitude >= -1) DEFAULT(-1), 
  AltitudeRange VARCHAR(15) DEFAULT('No information')
);
```

```{sql connection=birdstrikedb}
CREATE TABLE AircraftEngine
(
  AircraftModel VARCHAR(20),
  NumberOfEngines INT CHECK(NumberOfEngines >= 0) DEFAULT 2,
  FOREIGN KEY(AircraftModel) REFERENCES Aircraft(Model),
  PRIMARY KEY(AircraftModel, NumberOfEngines)
);
```

```{sql connection=birdstrikedb}
CREATE TABLE WildlifeStruckRange
(
  NumberOfWildlifeStruck INT PRIMARY KEY CHECK(NumberOfWildlifeStruck >= 1),
  StruckRange VARCHAR(20) DEFAULT('1')
)
```

```{sql connection=birdstrikedb}
CREATE TABLE IncidentDescription
(
  RecordID INT PRIMARY KEY AUTO_INCREMENT, 
  NumberWildlifeStruck INT DEFAULT(1),
  FlightImpact VARCHAR(25) DEFAULT('No information'),
  Damage VARCHAR(30) DEFAULT('No information'),
  PhaseOfFlight enum('Approach', 'Landing Roll', 'Climb', 
  'Take-off run', 'Descent','Taxi','Parked', 'No Information') DEFAULT('No Information'),
  SpecimenCollected BOOLEAN DEFAULT FALSE, 
  SpecimenSentToSmithsonian BOOLEAN DEFAULT FALSE, 
  Remarks VARCHAR(300) DEFAULT 'NONE', 
  WildlifeSize enum('small', 'medium', 'large') DEFAULT 'small',
  skyCondition enum('no cloud', 'some cloud', 'overcast') DEFAULT 'no cloud', 
  wildlifeSpecies VARCHAR(30) DEFAULT 'nothing struck', 
  totalCost FLOAT DEFAULT 0 CHECK(totalCost >= 0), 
  pilotWarned BOOLEAN DEFAULT FALSE, 
  feetAbove INT(4) CHECK(feetAbove >= -1) DEFAULT(-1), 
  peopleInjured INT CHECK(peopleInjured >=-1) DEFAULT(-1),
  FOREIGN KEY(feetabove) REFERENCES altitude(altitude),
  FOREIGN KEY(NumberWildlifeStruck) REFERENCES 
  WildlifeStruckRange(NumberOfWildlifeStruck)
)
```

```{sql connection=birdstrikedb}
CREATE TABLE FlightDetails
(
  IncidentID INT NOT NULL PRIMARY KEY,
  AirportName VARCHAR(80) NOT NULL DEFAULT 'Unknown',
  FlightDate DATE DEFAULT(DATE_FORMAT('%Y-%m-%d','1969-12-31')) NOT NULL,
  AircraftModel VARCHAR(20) NOT NULL DEFAULT 'No information', 
  Operator VARCHAR(50) DEFAULT 'No Information',
  FOREIGN KEY(AirportName) REFERENCES Airport(AirportName),
  FOREIGN KEY(AircraftModel) REFERENCES aircraft(Model),
  FOREIGN KEY(IncidentID) REFERENCES incidentdescription(RecordID)
)
```

```{sql connection=birdstrikedb}
CREATE TABLE IncidentPrecipitation
(
  incidentID INT, 
  Precipitation enum('None', 'Rain', 'Snow', 'Fog'),
  FOREIGN KEY(incidentID) references incidentdescription(RecordID),
  PRIMARY KEY(incidentID, Precipitation)
)
```


```{r}
dbDisconnect(birdstrikedb)
```


