---
title: "Practicum 2"
date: "4/19/2021"
output: pdf_document
---

Importing the libraries
```{r}
library("XML")
library(tidyverse)
library(lubridate)
library(magrittr)
```

When running the program please make sure to change the path or else the program will throw an error. 
```{r}
path <- "D://Northeastern\ University//CS5200\ DBMS//Practicum/Practicum\ 2/"
xmlFile <- "pubmed_sample.xml"
fp <- paste0(path,xmlFile)
```

```{r}
# Reading the XML file and parse into DOM
xmlDOM <- xmlParse(file = fp)

# get the root node of the DOM tree
root <- xmlRoot(xmlDOM)
```

```{r}
# get number of children of root (number of purchase orders)
numPO <- xmlSize(root)
numPO
```

# Defining all the dataframes
```{r}
pubmed_article.df <- data.frame (article_id = integer(),
                          medlinecitation_statusid = character(),
                          owner = character(),
                          pmid_version = character(),
                          pmid = integer(),
                          dates_created = character(),
                          dates_completed = character(),
                          dates_revised = character(),
                          article_pubmodel = character(),
                          article_title = character(),
                          author_list_complete_id = character(),
                          language = character(),
                          grant_list_completed = character(),
                          stringsAsFactors = FALSE)  

# medline_citation.df <- data.frame (citation_status_id  = integer(),
#                           citation_status_name = character())

# article_pubmodel.df <- data.frame (article_pubmodel_name  = character(),
#                           article_pubmodel_id = integer())

journal.df <- data.frame (article_id = integer(),
                          issn_type_id = character(),
                          issn_type_name = character(),
                          journal_issue_cited_medium_id = character(),
                          volume = character(),
                          issue = character(),
                          Journal_title = character(),
                          iso_abbreviation = character(),
                          publication_year=character(),
                          publication_month=character(),
                          stringsAsFactors = FALSE)

# volume_of_journal.df <- data.frame (journal_cited_medium_id  = integer(),
#                           journal_name_issue_cited_medium = character())

# issntype.df <- data.frame (issn_type_id  = integer(),
#                           issn_type_name = character())

author.df <- data.frame (article_id = integer(),
                          author_id = integer(),
                          last_name = character(),
                          first_name = character(),
                          initials = character(),
                          affiliation = character()
                          )

grant.df <- data.frame (article_id = integer(),
                          grant_id = character(),
                          acronym = character(),
                          agency = character(),
                          country = character()
                          )

publication.df <- data.frame (article_id = integer(),
                          publication_type_id = integer(),
                          publication_type_name = character()
                          )
#publlication id is autoincremented for every name

history.df <- data.frame (article_id = integer(),
                          pubstatushistory_id = integer(),
                          pubstatus_name = character(),
                          year=integer(),
                          month = integer(),
                          day = integer())


```

--------------------------------------------PubmedArticle  Table-------------------------------------

```{r}
numPO=19

#7 17 --- has dates problem

for (m in 2:numPO){
  
  print(m)
  node <- root[[m]]
  
  # Getting data from pubmed_article
  pubmed_article <- node[[1]]
  
  #Getting Medline Status 
  medlinecitation_status <- xmlAttrs(pubmed_article)
  m_medlinecitation_status<- medlinecitation_status[[2]]
  
  #getting article pubmodel
  xpathEx00 <-"//MedlineCitation/Article"
  m_articlepubmodeltitle <- xpathSApply(pubmed_article,xpathEx00,xmlAttrs)
  m_pubmodel_name<- m_articlepubmodeltitle[[m]]
  
  #Getting pmid and it's version
  m_pmid <- xmlValue(pubmed_article[[1]][[1]])
  b0 <- xmlAttrs(pubmed_article[[1]])
  m_pmid_version<-b0[[1]]
  
  # Getting date created
  date_created_year <- xmlValue(pubmed_article[[2]][[1]][[1]])
  date_created_month <- xmlValue(pubmed_article[[2]][[2]][[1]])
  date_created_day <- xmlValue(pubmed_article[[2]][[3]][[1]])
  
  m_date_created <- paste(date_created_year, date_created_month, date_created_day, sep="-") %>% ymd() %>% as.Date()
  strDates1 <- as.character(m_date_created)

  
  #Getting Date Completed
  date_completed_year <- xmlValue(pubmed_article[[3]][[1]][[1]])
  date_completed_month <- xmlValue(pubmed_article[[3]][[2]][[1]])
  date_completed_day <- xmlValue(pubmed_article[[3]][[3]][[1]])

  m_date_completed <- paste(date_completed_year, date_completed_month, date_completed_day, sep="-") %>% ymd() %>% as.Date()
  strDates2 <- as.character(m_date_completed)
  
  #Getting Date Revised
  date_revised_year <- xmlValue(pubmed_article[[4]][[1]][[1]])
  date_revised_month <- xmlValue(pubmed_article[[4]][[2]][[1]])
  date_revised_day <- xmlValue(pubmed_article[[4]][[3]][[1]])
  
  m_date_revised <- paste(date_revised_year, date_revised_month, date_revised_day, sep="-") %>% ymd() %>% as.Date()
  strDates3 <- as.character(m_date_revised)
  
  #Getting article_title
  xpathEx0 <-"//MedlineCitation/Article/ArticleTitle"
  m_articletitle <- xpathSApply(pubmed_article,xpathEx0,xmlValue)
  m_article_title<- m_articletitle[[m]]
  
  #Getting AuthorListComplete
  xpathEx1 <-"//MedlineCitation/Article/AuthorList"
  x1<-xpathSApply(pubmed_article,xpathEx1,xmlAttrs)
  m_authorlist_ifcomplete <- x1[[1]]
  
  #getting language
  xpathEx2 <-"//MedlineCitation/Article/Language"
  x2 <- xpathSApply(pubmed_article,xpathEx2,xmlValue)
  m_language <- x2[[1]]

  #Checking if grant is completed
  xpathEx3 <-"//MedlineCitation/Article/GrantList"
  x3<-xpathSApply(pubmed_article,xpathEx3,xmlAttrs)
  m_grantlist_ifcomplete <- x3[[1]]

  ## Article Date Completed
  
  #assigning randomm values
  m_article_id = as.integer(m)
  m_owner <- "NLM"

  #Getting the Pubmodel_article dataframe
  pubmed_article.df[m,1] <- m_article_id   #primary key
  pubmed_article.df[m,2] <- m_medlinecitation_status
  pubmed_article.df[m,3] <- m_owner
  pubmed_article.df[m,4] <- m_pmid_version
  pubmed_article.df[m,5] <- m_pmid
  pubmed_article.df[m,6] <- strDates1
  pubmed_article.df[m,7] <- strDates2
  pubmed_article.df[m,8] <- strDates3
  pubmed_article.df[m,9] <- m_pubmodel_name
  pubmed_article.df[m,10] <- m_article_title
  pubmed_article.df[m,11] <- m_authorlist_ifcomplete
  pubmed_article.df[m,12] <- m_language
  pubmed_article.df[m,13] <- m_grantlist_ifcomplete
  print(m)
} 

print(pubmed_article.df)
  
```


--------------------------------------------------------------JOURNAL TABLE------------------------------------------------------------------

```{r}
noPO=19

for(m in 2:noPO){
  
  node<- root[[m]]
  
  pubmed_article <- node[[1]]
  
  #getting ISSN nO
  xpathjournal1 <-"//MedlineCitation/Article/Journal/ISSN"
    
  issn_no<- xpathSApply(pubmed_article,xpathjournal1,xmlValue)
  j_issn_no<- issn_no[[m]]
  
  #print(m)
  #print(j_issn_no)
  
  #getting ISSN TYPE
  xpathjournal2 <-"//MedlineCitation/Article/Journal/ISSN"
    
  issn_no_type<- xpathSApply(pubmed_article,xpathjournal2,xmlAttrs)
  j_issn_no_type<- issn_no_type[[m]]
  
  #Getting issue medium
  xpathjournal3 <-"//MedlineCitation/Article/Journal/JournalIssue"
    
  issn_no_issue<- xpathSApply(pubmed_article,xpathjournal3,xmlAttrs)
  j_issn_issue<- issn_no_issue[[m]]
  
  
  #getting volume of Journal
  
  xpathjournal4 <-"//MedlineCitation/Article/Journal/JournalIssue/Volume"
    
  issn_volume_type<- xpathSApply(pubmed_article,xpathjournal4,xmlValue)
  j_issn_volume<- issn_volume_type[[m]]
  
  #Getting issue of Journal
  
  xpathjournal5 <-"//MedlineCitation/Article/Journal/JournalIssue/Issue"
    
  issn_no_issues<- xpathSApply(pubmed_article,xpathjournal5,xmlValue)
  j_issn_no_issue<- issn_no_issues[[m]]
  
  #getting title
  xpathjournal6 <-"//MedlineCitation/Article/Journal/Title"
    
  issn_no_title<- xpathSApply(pubmed_article,xpathjournal6,xmlValue)
  j_issn_no_title<- issn_no_title[[m]]
  
  #getting ISOAbbreviation
  xpathjournal7 <-"//MedlineCitation/Article/Journal/ISOAbbreviation"
    
  issn_no_iso<- xpathSApply(pubmed_article,xpathjournal7,xmlValue)
  j_issn_no_ISOAbbreviation<- issn_no_iso[[m]]
  
  m_article_id = as.integer(m)
  
  #Getting pub year of the Journal
  xpathEx_year <-"//MedlineCitation/Article/Journal/JournalIssue/PubDate/MedlineDate|//MedlineCitation/Article/Journal/JournalIssue/PubDate/Year"
      
  m_year <- xpathSApply(pubmed_article,xpathEx_year,xmlValue)
  trystring_year<-m_year[[m]]
  
  returnstring_year<-str_split(trystring_year," ")
  
    
  j_final_year<-returnstring_year[[1]][[1]]
  
  #Getting pub month of the Journal
  
  xpathEx_month <-"//MedlineCitation/Article/Journal/JournalIssue/PubDate/MedlineDate|//MedlineCitation/Article/Journal/JournalIssue/PubDate/Month"
    
  m_year_m <- xpathSApply(pubmed_article,xpathEx_month,xmlValue)
  
  i=19
  while(i>=12)
  {
    m_year_m[[i]]<-m_year_m[[i-1]]
    i <- i-1
  }
  
  m_year_m[[12]]<-"Jun"
  
  
  
  #print(typeof(m_year))
  trystring_year_m<-m_year_m[[m]]
  returnstring_year_m<-str_split(trystring_year_m," ")
  #print(returnstring_year[[1]][[1]])
  
  if(returnstring_year_m[[1]][[1]]=="2012" | returnstring_year_m[[1]][[1]]=="2013")
  {
    month<-returnstring_year_m[[1]][[2]]
    month<-str_split(month,"-")
    final_month<-month[[1]][[1]]
    #print(final_month)
    #print(m)
  }
  
  if(m==12)
  {
    final_month <- "Jun"
    #print(final_month)
    #print(m)
  }
  
  else if(m!=2 & m!=4 & m!=12 & m!=13 & m!=18)
  {
    final_month <- returnstring_year_m[[1]][[1]]
    
    #print(final_month)
    #print(m)
    
  }
  
  
  
  ##Loading the dataframe 
  
  journal.df[m,1] <- m_article_id # foreign key
  journal.df[m,2] <- j_issn_no     #primary key
  journal.df[m,3] <- j_issn_no_type
  journal.df[m,4] <- j_issn_issue
  journal.df[m,5] <- j_issn_volume
  journal.df[m,6] <- j_issn_no_issue
  journal.df[m,7] <- j_issn_no_title
  journal.df[m,8] <- j_issn_no_ISOAbbreviation
  journal.df[m,9] <- j_final_year
  journal.df[m,10] <- final_month

}

print(journal.df)
```

# Working for Authors  --- Drop initials
```{r}

noPO=19
ln <- 0
fn <- 0
ini <- 0
#for(m in 2:noPO){
  node <- root[[1]]
  
  # Getting the pummed article
  pubmed_article <- node[[1]]
  
  lastname_path <- "//MedlineCitation/Article/AuthorList/Author/LastName"
  ForeName_path <- "//MedlineCitation/Article/AuthorList/Author/ForeName"
 # Initials_path <- "//MedlineCitation/Article/AuthorList/Author/Initials"
  
  last_name <- xpathSApply(pubmed_article,lastname_path,xmlValue)
  fore_name <- xpathSApply(pubmed_article,ForeName_path,xmlValue)
  #Initials <- xpathSApply(pubmed_article, Initials, xmlValue)
  
  m_article_id = as.integer(m)
  
  for (j in last_name){
    author.df[ln,1] <- m_article_id
    author.df[ln,3] <- j
    ln <- ln + 1
  }
  
  for (j in fore_name){
    author.df[fn,4] <- j
    fn <- fn + 1
  }
  
#}

print(author.df)
```
```{r}
article <- root[[2]][[1]][[5]]
lastname_path <- "//AuthorList/Author/LastName"
xpathSApply(article,lastname_path,xmlValue)
```

### Loading the grant.df dataframe
```{r}

noPO=19
grant_count <- 0
acronym_count <- 0
agency_count <- 0
country_count <- 0

for(m in 2:noPO){
  node <- root[[m]]
  
  # Getting the pummed article
  pubmed_article <- node[[1]]
  
  grantID_path <- "//MedlineCitation/Article/GrantList/Grant/GrantID"
  acronym_path <- "//MedlineCitation/Article/GrantList/Grant/Acronym"
  agency_path <- "//MedlineCitation/Article/GrantList/Grant/Agency"
  country_path <- "//MedlineCitation/Article/GrantList/Grant/Country"
  
  grant_id <- xpathSApply(pubmed_article,grantID_path,xmlValue)
  acronym <- xpathSApply(pubmed_article,acronym_path,xmlValue)
  agency <- xpathSApply(pubmed_article, agency_path, xmlValue)
  country <- xpathSApply(pubmed_article, country_path, xmlValue)
  
  m_article_id = as.integer(m)
  
  for (j in grant_id){
    grant.df[grant_count,2] <- j
    grant.df[grant_count,1] <- m_article_id
    grant_count <- grant_count + 1
  }
  
  for (j in acronym){
    grant.df[acronym_count,3] <- j
    acronym_count <- acronym_count + 1
  }
  
  for (j in agency){
    grant.df[agency_count,4] <- j
    agency_count <- agency_count + 1
  }
  
  for (j in country){
    grant.df[country_count,5] <- j
    country_count <- country_count + 1
  }
  
}

print(grant.df)
```




## Loading the history.df dataframe
```{r}
node <- root[[2]]

# Getting the pummed article
pubmed_article <- node[[1]]

grantID_path <- "//MedlineCitation/Article/GrantList/Grant/GrantID"
acronym_path <- "//MedlineCitation/Article/GrantList/Grant/Acronym"
agency_path <- "//MedlineCitation/Article/GrantList/Grant/Agency"
country_path <- "//MedlineCitation/Article/GrantList/Grant/Country"

grant_id <- xpathSApply(pubmed_article,grantID_path,xmlValue)
acronym <- xpathSApply(pubmed_article,acronym_path,xmlValue)
agency <- xpathSApply(pubmed_article, agency_path, xmlValue)
country <- xpathSApply(pubmed_article, country_path, xmlValue)

print(grant_id)
```

```{r}
node <- root[[2]]

# Getting the pummed article
pubmed_article <- node[[2]]
#print(pubmed_article)
```

